services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_PORT
        value: "$PORT"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_HOST
        value: "n8n-service-veym.onrender.com"
      - key: WEBHOOK_URL
        value: "https://n8n-service-veym.onrender.com/"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "yourpassword"
      - key: N8N_ENCRYPTION_KEY
        value: "your_random_encryption_key"
      - key: GENERIC_TIMEZONE
        value: "Asia/Kolkata"
      - key: NODE_ENV
        value: "production"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
